### ISSUE TITLE
 MSDiscoveryServiceInfoCollectionFetcher returns V1.0 URLs

### ISSUE THREAD

**Issue by siddheshcnaik** [OfficeDev/Office-365-Discovery-SDK-iOS#1]
Hi,
We are using following code to discover endpoints and use them with iOS Outlook SDK

Office365ClientFetcher *fetcher = [[Office365ClientFetcher alloc] init];

```
[fetcher
 fetchDiscoveryClient:^(MSDiscoveryClient *discoveryClient, O365ServiceProvider *provider, AuthenticationStatus authStatus) {
     if (discoveryClient != nil && authStatus == AuthenticationStatus_Success) {
         MSDiscoveryServiceInfoCollectionFetcher *servicesInfoFetcher = [discoveryClient services];
         [servicesInfoFetcher readWithCallback:^(NSArray* response, MSOrcError *error) {
             NSMutableDictionary *keysAndValues = [[NSMutableDictionary alloc] init];
             if ((response.count > 0) && (error == nil)) {
                 for (MSDiscoveryServiceInfo *service in response) {
                     [keysAndValues setObject:service.serviceEndpointUri forKey:service.capability];
                     [keysAndValues setObject:service.serviceResourceId forKey:[service.capability stringByAppendingString:@"ResourceID"]];
                 }
             }
             else {
                 keysAndValues = defaultServices.mutableCopy;
             }
             NSMutableArray *keys = [[NSMutableArray alloc] init];
             NSUserDefaults *userDefaults = [NSUserDefaults standardUserDefaults];
             for (NSString *key in keysAndValues) {
                 [userDefaults setObject:keysAndValues[key] forKey:key];
                 [keys addObject:key];
             }
             [userDefaults setObject:keys forKey:kOffice365Keys];
             [userDefaults synchronize];
             if (callBack != nil) {
                 callBack(AuthenticationStatus_Success);
             }
         }];

     }
     else {
         NSLog(@"Error in the authentication during service discovery.");
         if (callBack) {
             callBack(authStatus);
         }
     }
 }];
```

And in Office365ClientFetcher
- (void)fetchDiscoveryClient:(void (^)(MSDiscoveryClient *discoveryClient, O365ServiceProvider *provider, AuthenticationStatus authStatus))callback
  {
  dispatch_async(internalQueue, ^{
      if (self.authenticationManager == nil) {
          self.authenticationManager = [[AuthenticationManager alloc] init];
      }
      [self.authenticationManager acquireAuthTokenWithResourceId:@"https://api.office.com/discovery/"
                                               completionHandler:^(AuthenticationStatus authStatus)
       {
           if (authStatus == AuthenticationStatus_Success) {
               callback([[MSDiscoveryClient alloc] initWithUrl:@"https://api.office.com/discovery/v2.0/me/"
                                            dependencyResolver:self.authenticationManager.dependencyResolver],
                        [[O365ServiceProvider alloc] initWithUserId:self.authenticationManager.logInUser andOptionalToken:self.authenticationManager.accessToken],
                        authStatus);
  
  ```
       }
       else {
           callback(nil, nil, authStatus);
       }
   }];
  ```
  
  });
  }

In Pod file we have
pod 'MSOutlook-SDK-iOS'
pod 'MSOffice365-Discovery-SDK-iOS'

When we execute the code for discovering end points, we get end point URLs pointing to V1.0. This causes the Outlook SDK requst to fail with error.

Are there any other changes in the  MSDiscoveryServiceInfoCollectionFetcher to retrieve Office 365 V2.0 URLs? 

Could you please help?

**Comment by sumurthy** [comment]
This repo is being archived as the discovery API that is needed for this to work is deprecated.
